#!/usr/share/env bash
; '
Archivo que hace un indice de contenido multimedia en discos
normalmente se espera la ejecucion en menos de un minuto
'
echo -e " ruta a la raiz: "
read RAIZ
cd RAIZ
mkdir ~/.indexer
find . > ~/.indexer/indexfs.txt
find . | xargs exiftool > ~/.indexer/metadata.txt
MEDIAFS=('.pdf' '.mp4' '.mp3' '.xls' '.jpg')
find . | grep MEDIAFS[@]
